### PR TITLE
0.5.4 release

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by hariharan-a** [comment]
Hi Abhi,

I am trying to compile latest ydk-cpp in Centos 7. Getting the following errors:

[root@localhost ~]# cd ydk-cpp/core/ydk/
[root@localhost ydk]# mkdir build
[root@localhost ydk]# cd build/
[root@localhost build]# cmake ..
CMake Error at CMakeLists.txt:2 (cmake_policy):
  Policy "CMP0048" is not known to this version of CMake.


CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_VERSION_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_VERSION_COMPILER
CMake Error: Could not find cmake module file: /root/ydk-cpp/core/ydk/build/CMakeFiles/2.8.12.2/CMakeVERSIONCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_0.5.4_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_0.5.4_COMPILER
CMake Error: Could not find cmake module file: /root/ydk-cpp/core/ydk/build/CMakeFiles/2.8.12.2/CMake0.5.4Compiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_LANGUAGES_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_LANGUAGES_COMPILER
CMake Error: Could not find cmake module file: /root/ydk-cpp/core/ydk/build/CMakeFiles/2.8.12.2/CMakeLANGUAGESCompiler.cmake
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
CMake Error: Could not find cmake module file: CMakeVERSIONInformation.cmake
CMake Error: Could not find cmake module file: CMake0.5.4Information.cmake
CMake Error: Could not find cmake module file: CMakeLANGUAGESInformation.cmake
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error: CMAKE_VERSION_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_0.5.4_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_LANGUAGES_COMPILER not set, after EnableLanguage
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.1") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.5") 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") 
CMake Error at samples/CMakeLists.txt:2 (cmake_policy):
  Policy "CMP0048" is not known to this version of CMake.


CMake Error at tests/CMakeLists.txt:2 (cmake_policy):
  Policy "CMP0048" is not known to this version of CMake.


-- Configuring incomplete, errors occurred!
See also "/root/ydk-cpp/core/ydk/build/CMakeFiles/CMakeOutput.log".

**Comment by ghost** [comment]
Hi Hariharan,
Please see the requirements for [Centos here](https://github.com/CiscoDevNet/ydk-gen#linux). Following these steps should help you to build.

**Comment by hariharan-a** [comment]
Thanks Abhi.  I am able to proceed. Now make fails with this:

/root/ydk-cpp/core/ydk/src/json.hpp:67:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
         #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
          ^
make[2]: *** [CMakeFiles/ydk.dir/src/opendaylight_parser.cpp.o] Error 1
make[1]: *** [CMakeFiles/ydk.dir/all] Error 2

----------
I have the following gcc version.

[root@localhost build]# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ghost** [comment]
Glad you could progress further. Can you try the below steps from your cmake build directory?

$ cd ..
$ rm -rf build && mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ ..
$ make
$ sudo make install

**Comment by hariharan-a** [comment]
Hi Abhi,

I am able to compile core, openconfig and ietf. But cisco-ios-xr seems to be really slow and at some point getting a compilation error. Is this expected ?

[root@localhost build]# tail -f nohup.out 
Scanning dependencies of target ydk_cisco_ios_xr
[  0%] Building CXX object CMakeFiles/ydk_cisco_ios_xr.dir/ydk/models/cisco_ios_xr/generated_entity_lookup.cpp.o
[  0%] Building CXX object CMakeFiles/ydk_cisco_ios_xr.dir/ydk/models/cisco_ios_xr/Cisco_IOS_XR_procmem_oper.cpp.o
[  0%] Building CXX object CMakeFiles/ydk_cisco_ios_xr.dir/ydk/models/cisco_ios_xr/fragmented/Cisco_IOS_XR_pmengine_oper_0.cpp.o
[

**Comment by hariharan-a** [comment]
Hi Abhi,

I got core, ietf, openconfig and cisco-ios-xr compiled and installed. Now I am trying to compile core/samples.

Did a similar cmake and make. Getting the following link errors:

make[1]: *** [CMakeFiles/bgp_xr_read.dir/all] Error 2
/usr/local/lib/libydk_cisco_ios_xr.a(generated_entity_lookup.cpp.o): In function `ydk::cisco_ios_xr_augment_lookup_tables()':
/root/ydk-cpp/cisco-ios-xr/ydk/models/cisco_ios_xr/generated_entity_lookup.cpp:(.text+0x9d): undefined reference to `ydk::ydk_global_capabilities'
/root/ydk-cpp/cisco-ios-xr/ydk/models/cisco_ios_xr/generated_entity_lookup.cpp:(.text+0x1d3): undefined reference to `ydk::ydk_global_capabilities'
/root/ydk-cpp/cisco-ios-xr/ydk/models/cisco_ios_xr/generated_entity_lookup.cpp:(.text+0x309): undefined reference to `ydk::ydk_global_capabilities'
/root/ydk-cpp/cisco-ios-xr/ydk/models/cisco_ios_xr/generated_entity_lookup.cpp:(.text+0x43f): undefined reference to `ydk::ydk_global_capabilities'
/root/ydk-cpp/cisco-ios-xr/ydk/models/cisco_ios_xr/generated_entity_lookup.cpp:(.text+0x575): undefined reference to `ydk::ydk_global_capabilities'
/usr/local/lib/libydk_cisco_ios_xr.a(generated_entity_lookup.cpp.o):/root/ydk-cpp/cisco-ios-xr/ydk/models/cisco_ios_xr/generated_entity_lookup.cpp:(.text+0x6ab): more undefined references to `ydk::ydk_global_capabilities' follow
collect2: error: ld returned 1 exit status
make[2]: *** [bgp_xr_opendaylight] Error 1
make[1]: *** [CMakeFiles/bgp_xr_opendaylight.dir/all] Error 2
m

**Comment by ghost** [comment]
Hmm.. Thats strange. I will try to reproduce this and let you know.

**Comment by ghost** [comment]
Sorry I'm not able to reproduce this issue. From the log, it looks like an issue with incompatible versions of core and cisco-ios-xr. Did you by any chance, have different versions installed? Can you try recompiling/installing the core?

**Comment by hariharan-a** [comment]
will do. I am assuming for all the cmakes I should use the CLANG compiler option that you provided earlier ?

**Comment by ghost** [comment]
Yes

**Comment by hariharan-a** [comment]
The issue persists. Is it possible to have a webex if you would like to debug live ? How about say tuesday/wednesday sometime in PDT ?

[root@rex4rd samples]# rm -rf build
[root@rex4rd samples]# mkdir build
[root@rex4rd samples]# cd build/
[root@rex4rd build]# !cmake
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ ..
-- The C compiler identification is Clang 3.4.2
-- The CXX compiler identification is Clang 3.4.2
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/ydk-cpp/core/samples/build
[root@rex4rd build]# make -j 4
Scanning dependencies of target bgp_restconf
Scanning dependencies of target bgp_xr_opendaylight
Scanning dependencies of target bgp_xr_read
Scanning dependencies of target bgp_create
[  2%] Building CXX object CMakeFiles/bgp_restconf.dir/bgp_restconf.cpp.o
[  5%] Building CXX object CMakeFiles/bgp_xr_opendaylight.dir/bgp_xr_opendaylight.cpp.o
[  7%] Building CXX object CMakeFiles/bgp_xr_read.dir/bgp_xr_read.cpp.o
[ 10%] Building CXX object CMakeFiles/bgp_create.dir/bgp_create.cpp.o
[ 12%] Building CXX object CMakeFiles/bgp_restconf.dir/args_parser.cpp.o
[ 15%] Building CXX object CMakeFiles/bgp_xr_read.dir/args_parser.cpp.o
[ 17%] Building CXX object CMakeFiles/bgp_create.dir/args_parser.cpp.o
[ 20%] Linking CXX executable bgp_restconf
[ 23%] Linking CXX executable bgp_xr_read
[ 25%] Linking CXX executable bgp_create
[ 28%] Building CXX object CMakeFiles/bgp_xr_opendaylight.dir/args_parser.cpp.o
[ 30%] Linking CXX executable bgp_xr_opendaylight
/usr/local/lib/libydk_openconfig.a(openconfig_bgp_0.cpp.o): In function `ydk::openconfig_bgp::Bgp::Bgp()':
/root/ydk-cpp/openconfig/ydk/models/openconfig/fragmented/openconfig_bgp_0.cpp:(.text+0x11): undefined reference to `ydk::Entity::Entity()'
/root/ydk-cpp/openconfig/ydk/models/openconfig/fragmented/openconfig_bgp_0.cpp:(.text+0x254): undefined reference to `ydk::Entity::~Entity()'
/usr/local/lib/libydk_openconfig.a(openconfig_bgp_0.cpp.o): In function `ydk::openconfig_bgp::Bgp::~Bgp()':
/root/ydk-cpp/openconfig/ydk/models/openconfig/fragmented/openconfig_bgp_0.cpp:(.text+0x2af): undefined reference to `ydk::Entity::~Entity()'
/usr/local/lib/libydk_openconfig.a(openconfig_bgp_0.cpp.o): In function `ydk::openconfig_bgp::Bgp::Global::Global()':

**Comment by ghost** [comment]
Sure. But any time next week is a bit difficult. If we could meet today or Friday that'd be great

**Comment by hariharan-a** [comment]
OK. Lets do it today. I am reachable at hari@packetdesign.com

**Pull request merged**
